services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20-bullseye
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    command: sleep infinity
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/desi_digital_hub?schema=public"
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: desi_digital_hub
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules:
